CREATE TABLE [dbo].[AppRoles]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [RoleName] NVARCHAR(50) NOT NULL, 
	[DisplayName] NVARCHAR(50) NOT NULL,
	[Category] NVARCHAR(50) NULL, 
    [IsEnabled] BIT NOT NULL
)
